version: '3.8'

networks:
    dev:

services:
    nginx:
        image: nginx:stable-alpine
        ports:
            - "8080:80"
        volumes:
            - './nginx.conf:/etc/nginx/nginx.conf'
        depends_on:
            - backend
            - front
        networks:
            - dev

    backend:
        build:
            context: .
        ports:
            - "8002:8002"
        networks:
            - dev

    front:
        build:
            context: .
        ports:
            - "8003:8003"
        networks:
            - dev
